Repository Real-Dev-Squad/website-welcome, pull requests merged in 2021-03, with the labels that each got.

#100 Change in design of the home page of welcome site
  css/common/main.css
  css/pages/index.css
  index.html
Labels: enhancement

#106 Changes in CONTRIBUTING.md: Rebasing instead of merging, change in PR base
  CONTRIBUTING.md
Labels: documentation

#113 Adding .editorconfig file and rules to it.
  .editorconfig
Labels: enhancement

#119 Adds `cd website-welcome` step in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#120 Sets up Prettier CLI for consistent formatting of code
  .editorconfig
  .prettierrc.json
  code-of-conduct.html
  discord.html
  faq.html
  icons.json
  index.html
  js/login.js
  navbar.html
  package-lock.json
  package.json
Labels: DX, enhancement

#130 Setting up prettier pre-commit hook
  README.md
  css/pages/index.css
  package-lock.json
  package.json
Labels: documentation, enhancement

#135 Addition of nonreferrer attribute in links
  CONTRIBUTING.md
  index.html
Labels: enhancement
